/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack_principal;

import java.io.IOException;
import javax.swing.JOptionPane;
import pack_entidades.ImagenFondo;
import pack_login.frm_login;
import pack_registro.frm_acerca;

import pack_registro.frm_registro_cita;

import pack_registro.frm_registro_paciente;
import pack_registro.frm_registro_doctor;
import pack_registro.frm_trabajador;
import pack_reporte.reporte_cita_medica;
import pack_reporte.reporte_doctor;
import pack_reporte.reporte_paciente;
import pack_reporte.reporte_trabajador;

/**
 *
 * @author JHONNY BRYAN
 */
public class frm_menu extends javax.swing.JFrame {

   
     ImagenFondo imajen_fondo =new ImagenFondo();
     
   

    
    
    
    
    public frm_menu() {
        initComponents(); 
        //this.setContentPane(dpEscritorio);
        this.setExtendedState(frm_menu.MAXIMIZED_BOTH); 
        dp_escritorio.setBorder(new ImagenFondo());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        dp_escritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mi_mant_trabajador = new javax.swing.JMenuItem();
        mi_mant_doctor = new javax.swing.JMenuItem();
        mi_mant_paciente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mi_operaciones_cita = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mi_reporte_trabajador = new javax.swing.JMenuItem();
        mi_reporte_doctor = new javax.swing.JMenuItem();
        mi_reporte_paciente = new javax.swing.JMenuItem();
        mi_reporte_cita = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/boton trabajador.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/boton_doctor.jpg"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/boton_paciente.jpg"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/boton reporte.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/boton calculadora.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/boton salir.png"))); // NOI18N
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        javax.swing.GroupLayout dp_escritorioLayout = new javax.swing.GroupLayout(dp_escritorio);
        dp_escritorio.setLayout(dp_escritorioLayout);
        dp_escritorioLayout.setHorizontalGroup(
            dp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dp_escritorioLayout.setVerticalGroup(
            dp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        jMenu3.setText("Mantenimiento");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        mi_mant_trabajador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        mi_mant_trabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/trabajador_menu.png"))); // NOI18N
        mi_mant_trabajador.setText("Trabajador");
        mi_mant_trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_mant_trabajadorActionPerformed(evt);
            }
        });
        jMenu3.add(mi_mant_trabajador);

        mi_mant_doctor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        mi_mant_doctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/menu_doctor.jpg"))); // NOI18N
        mi_mant_doctor.setText("Doctor");
        mi_mant_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_mant_doctorActionPerformed(evt);
            }
        });
        jMenu3.add(mi_mant_doctor);

        mi_mant_paciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        mi_mant_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/menu_paciente.jpg"))); // NOI18N
        mi_mant_paciente.setText("Paciente");
        mi_mant_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_mant_pacienteActionPerformed(evt);
            }
        });
        jMenu3.add(mi_mant_paciente);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Operaciones");

        mi_operaciones_cita.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        mi_operaciones_cita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/menu_cita.jpg"))); // NOI18N
        mi_operaciones_cita.setText("Cita medica");
        mi_operaciones_cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_operaciones_citaActionPerformed(evt);
            }
        });
        jMenu4.add(mi_operaciones_cita);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Reporte");

        mi_reporte_trabajador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        mi_reporte_trabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/trabajador_menu.png"))); // NOI18N
        mi_reporte_trabajador.setText("Trabajador");
        mi_reporte_trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_reporte_trabajadorActionPerformed(evt);
            }
        });
        jMenu5.add(mi_reporte_trabajador);

        mi_reporte_doctor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        mi_reporte_doctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/menu_doctor.jpg"))); // NOI18N
        mi_reporte_doctor.setText("Doctor");
        mi_reporte_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_reporte_doctorActionPerformed(evt);
            }
        });
        jMenu5.add(mi_reporte_doctor);

        mi_reporte_paciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        mi_reporte_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/menu_paciente.jpg"))); // NOI18N
        mi_reporte_paciente.setText("Pacientes");
        mi_reporte_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_reporte_pacienteActionPerformed(evt);
            }
        });
        jMenu5.add(mi_reporte_paciente);

        mi_reporte_cita.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        mi_reporte_cita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/menu_cita.jpg"))); // NOI18N
        mi_reporte_cita.setText("Cita Medica");
        mi_reporte_cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_reporte_citaActionPerformed(evt);
            }
        });
        jMenu5.add(mi_reporte_cita);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Herramientas");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/menu_calculadora.png"))); // NOI18N
        jMenuItem1.setText("Calculadora");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/notas menu.png"))); // NOI18N
        jMenuItem2.setText("Block de Notas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("Ayuda");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/interroga_menu.png"))); // NOI18N
        jMenuItem3.setText("Acerca Del Sistema");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/manual_menu.png"))); // NOI18N
        jMenuItem4.setText("Manual Del Sistema");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Salir");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/cerrar menu.png"))); // NOI18N
        jMenuItem5.setText("Salir Del Sistema");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/triangulo.png"))); // NOI18N
        jMenuItem6.setText("Cerrar Sesíon");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem6);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
            .addComponent(dp_escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dp_escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            try        
    {
        Runtime rt = Runtime.getRuntime();           
        Process p = rt.exec("calc");            
        p.waitFor();        
    }    
        
        
    catch (IOException ioe )       
    {            
        ioe.printStackTrace();
    }  
        
    catch (InterruptedException ie )
    {            
        ie.printStackTrace();     
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void mi_mant_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_mant_pacienteActionPerformed
        frm_registro_paciente rp = new frm_registro_paciente();
        rp.setVisible(true);
        dp_escritorio.add(rp);
        rp.toFront();
    }//GEN-LAST:event_mi_mant_pacienteActionPerformed

    private void mi_mant_trabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_mant_trabajadorActionPerformed
      frm_trabajador trabajador = new frm_trabajador();
        trabajador.setVisible(true);
        dp_escritorio.add(trabajador);
        trabajador.toFront();
    }//GEN-LAST:event_mi_mant_trabajadorActionPerformed

    private void mi_mant_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_mant_doctorActionPerformed
      frm_registro_doctor doctor = new frm_registro_doctor();
        doctor.setVisible(true);
        dp_escritorio.add(doctor);
        doctor.toFront();
        
        
        
    }//GEN-LAST:event_mi_mant_doctorActionPerformed

    private void mi_operaciones_citaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_operaciones_citaActionPerformed
       
        frm_registro_cita rp = new frm_registro_cita();
        rp.setVisible(true);
        dp_escritorio.add(rp);
        rp.toFront();
    }//GEN-LAST:event_mi_operaciones_citaActionPerformed

    private void mi_reporte_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_reporte_doctorActionPerformed
         reporte_doctor rd = new reporte_doctor();
        rd.setVisible(true);
        dp_escritorio.add(rd);
        rd.toFront();
        
    }//GEN-LAST:event_mi_reporte_doctorActionPerformed

    private void mi_reporte_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_reporte_pacienteActionPerformed
        reporte_paciente rd = new reporte_paciente();
        rd.setVisible(true);
        dp_escritorio.add(rd);
        rd.toFront();
        
    }//GEN-LAST:event_mi_reporte_pacienteActionPerformed

    private void mi_reporte_citaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_reporte_citaActionPerformed
        reporte_cita_medica rd = new reporte_cita_medica();
        rd.setVisible(true);
        dp_escritorio.add(rd);
        rd.toFront();
        
        
    }//GEN-LAST:event_mi_reporte_citaActionPerformed

    private void mi_reporte_trabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_reporte_trabajadorActionPerformed
        reporte_trabajador rd = new reporte_trabajador();
        rd.setVisible(true);
        dp_escritorio.add(rd);
        rd.toFront();
        
        
        
        
        
        
    }//GEN-LAST:event_mi_reporte_trabajadorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
           try        
    {
        Runtime rt = Runtime.getRuntime();           
        Process p = rt.exec("calc");            
        p.waitFor();        
    }    
        
        
    catch (IOException ioe )       
    {            
        ioe.printStackTrace();
    }  
        
    catch (InterruptedException ie )
    {            
        ie.printStackTrace();     
    }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
           
        try        
    {
        Runtime rt = Runtime.getRuntime();           
        Process p = rt.exec("notepad");            
        p.waitFor();        
    }    
        
        
    catch (IOException ioe )       
    {            
        ioe.printStackTrace();
    }  
        
    catch (InterruptedException ie )
    {            
        ie.printStackTrace();     
    }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         int x;
        x=JOptionPane.showConfirmDialog(null, "Desea salir?");
        if(x==0)
            System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       frm_login log = new frm_login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       frm_trabajador trabajador = new frm_trabajador();
        trabajador.setVisible(true);
        dp_escritorio.add(trabajador);
        trabajador.toFront();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         frm_registro_doctor doctor = new frm_registro_doctor();
        doctor.setVisible(true);
        dp_escritorio.add(doctor);
        doctor.toFront();
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        frm_registro_paciente rp = new frm_registro_paciente();
        rp.setVisible(true);
        dp_escritorio.add(rp);
        rp.toFront();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          frm_registro_cita rp = new frm_registro_cita();
        rp.setVisible(true);
        dp_escritorio.add(rp);
        rp.toFront();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        reporte_cita_medica rd = new reporte_cita_medica();
        rd.setVisible(true);
        dp_escritorio.add(rd);
        rd.toFront();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         frm_acerca rd = new frm_acerca();
        rd.setVisible(true);
        dp_escritorio.add(rd);
        rd.toFront(); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
           frm_login log = new frm_login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       try{
          String url = "src\\pack_manual\\MANUAL DE USUARIO.pdf";
        ProcessBuilder p = new ProcessBuilder();
        p.command("cmd.exe","/C",url);
        p.start();  
        
        }catch(IOException ex){
            
        }
    
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dp_escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mi_mant_doctor;
    private javax.swing.JMenuItem mi_mant_paciente;
    private javax.swing.JMenuItem mi_mant_trabajador;
    private javax.swing.JMenuItem mi_operaciones_cita;
    private javax.swing.JMenuItem mi_reporte_cita;
    private javax.swing.JMenuItem mi_reporte_doctor;
    private javax.swing.JMenuItem mi_reporte_paciente;
    private javax.swing.JMenuItem mi_reporte_trabajador;
    // End of variables declaration//GEN-END:variables
}
